name: firebase_admob_example
description: Demonstrates how to use the firebase_admob plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_admob:
    path: ../
  firebase_core: ^0.4.2+1

dev_dependencies:
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
