name: firebase_admob
description: Flutter plugin for Firebase AdMob, supporting
  banner, interstitial (full-screen), and rewarded video ads
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob
version: 0.9.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebaseadmob
        pluginClass: FirebaseAdMobPlugin
      ios:
        pluginClass: FLTFirebaseAdMobPlugin

dependencies:
  meta: ^1.0.4
  platform: ^2.0.0
  flutter:
    sdk: flutter
  firebase_core: ^0.4.2+1

dev_dependencies:
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter
  mockito: ^3.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
